version: '3'

networks:
    infonetwork:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: ${APP_NAME}_nginx
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:rw
            - ./docker/logs//nginx:/var/logs/nginx:rw
        depends_on:
            - php
            - postgres
        networks:
            - infonetwork

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ${APP_NAME}_php
        volumes:
            - ./:/var/www/html
        networks:
            - infonetwork

    postgres:
        image: postgres:15-alpine
        container_name: ${APP_NAME}_postgres
        restart: unless-stopped
        volumes:
            - ./docker/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        networks:
            - infonetwork
