CURRENT_BRANCH := $(shell git rev-parse --abbrev-ref HEAD)

up-dev:
    docker-compose up -f="./docker/docker-compose.yml" up -d

pint:
	./vendor/bin/pint

pest:
	./vendor/bin/pest

pre-commit:
	make pint
	make pest

push:
	git add .
	git commit -m "♻️ refactor: $(m)" -m "This commit is auto-generated by Makefile"
	git push origin $(CURRENT_BRANCH)

push-routine:
	make pre-commit
	make push m="running push routine"

run-dev:
	php artisan serve
